//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsuVina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public string iShipmentd { get; set; }
        public string Orderid { get; set; }
        public string TrackingNumber { get; set; }
        public string TotalWeight { get; set; }
    }
}
